import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

type User={id:string;name:string;email:string;role:'admin'|'operator'};
type Patient={id:string;name:string;phone:string;journey_status:string;contact_source:string;care_alert:string;next_contact_on:string|null;assigned_user_name:string;version:number;birth_date?:string|null;guardian_name?:string|null;notes?:string;archived_at?:string|null};
type TimelineItem={id:string;kind:string;type:string;description:string;occurred_at:string;author:string};
const statuses:{[key:string]:string}={new_lead:'Novo lead',screening:'Triagem',assessment_scheduled:'Avaliação marcada',proposal:'Em proposta',sale_completed:'Venda realizada',adaptation:'Adaptação',follow_up:'Acompanhamento',inactive:'Inativo'};
const sources:{[key:string]:string}={referral:'Indicação',whatsapp:'WhatsApp',instagram:'Instagram',google:'Google',walk_in:'Passou na clínica',other:'Outro'};
const eventTypes:{[key:string]:string}={call:'Ligação',whatsapp:'WhatsApp',consultation:'Consulta',device_adjustment:'Ajuste de aparelho',cleaning:'Limpeza',maintenance:'Manutenção',exchange:'Troca',warranty:'Garantia',clinical_note:'Observação clínica',scheduled_return:'Retorno programado'};
const date=(value:string|null|undefined)=>value?new Intl.DateTimeFormat('pt-BR').format(new Date(`${value}T12:00:00`)):'Não informado';
async function api(path:string,options?:RequestInit){const response=await fetch(path,options);if(response.status===204)return null;const body=await response.json();if(!response.ok)throw new Error(body.title??'Não foi possível concluir');return body;}

function PatientForm({patient,onDone,onCancel}:{patient?:Patient;onDone:(id:string,message?:string)=>void;onCancel:()=>void}){
  const [error,setError]=useState(''),[saving,setSaving]=useState(false);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setError('');setSaving(true);const values=Object.fromEntries(new FormData(event.currentTarget));try{const payload={...values,version:patient?.version,birthDate:values.birthDate||null,guardianName:values.guardianName||null,nextContactOn:values.nextContactOn||null};const body=await api(patient?`/api/patients/${patient.id}`:'/api/patients',{method:patient?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});onDone(patient?.id??body.id,body?.warning??'Ficha salva.');}catch(reason){setError((reason as Error).message);}finally{setSaving(false);}}
  return <form className="panel form" onSubmit={submit} aria-label={patient?'Editar paciente':'Novo paciente'}><div className="section-title"><h2>{patient?'Editar ficha':'Novo paciente'}</h2><button type="button" className="secondary" onClick={onCancel}>Cancelar</button></div>{error&&<p className="error" role="alert">{error}</p>}<div className="fields"><label>Nome completo<input name="name" defaultValue={patient?.name} minLength={2} required autoFocus/></label><label>Telefone ou WhatsApp<input name="phone" type="tel" defaultValue={patient?.phone} inputMode="tel" minLength={10} required/></label><label>Status<select name="status" defaultValue={patient?.journey_status??'new_lead'}>{Object.entries(statuses).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>Origem<select name="contactSource" defaultValue={patient?.contact_source??'other'}>{Object.entries(sources).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label></div><details open={Boolean(patient)}><summary>Mais informações</summary><div className="fields"><label>Próximo contato<input name="nextContactOn" type="date" defaultValue={patient?.next_contact_on??''}/></label><label>Data de nascimento<input name="birthDate" type="date" defaultValue={patient?.birth_date??''}/></label><label>Responsável pelo paciente<input name="guardianName" defaultValue={patient?.guardian_name??''}/></label><label className="wide">Alerta de cuidado<textarea name="careAlert" rows={2} defaultValue={patient?.care_alert??''}/></label><label className="wide">Observações<textarea name="notes" rows={3} defaultValue={patient?.notes??''}/></label></div></details><button disabled={saving}>{saving?'Salvando…':'Salvar paciente'}</button></form>;
}

function PatientRecord({id,onBack}:{id:string;onBack:()=>void}){
  const [patient,setPatient]=useState<Patient|null>(null),[timeline,setTimeline]=useState<TimelineItem[]>([]),[editing,setEditing]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
  async function load(){try{const [detail,history]=await Promise.all([api(`/api/patients/${id}`),api(`/api/patients/${id}/timeline`)]);setPatient(detail.patient);setTimeline(history.items);}catch(reason){setError((reason as Error).message);}}
  useEffect(()=>{load();},[id]);
  async function addEvent(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setError('');const form=event.currentTarget;try{await api(`/api/patients/${id}/events`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))});form.reset();setMessage('Interação registrada.');await load();}catch(reason){setError((reason as Error).message);}}
  async function archive(){if(!confirm('Arquivar este paciente? O histórico será preservado.'))return;try{await api(`/api/patients/${id}/archive`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({version:patient!.version})});onBack();}catch(reason){setError((reason as Error).message);}}
  if(!patient)return <section className="panel" aria-live="polite">{error||'Carregando ficha…'}</section>;
  if(editing)return <PatientForm patient={patient} onCancel={()=>setEditing(false)} onDone={async(_id,text)=>{setMessage(text??'Ficha salva.');setEditing(false);await load();}}/>;
  return <><button className="back" onClick={onBack}>← Voltar para pacientes</button>{message&&<p className="success" role="status">{message}</p>}{error&&<p className="error" role="alert">{error}</p>}<section className="panel record"><div className="section-title"><div><h2>{patient.name}</h2><p>{patient.phone} · {statuses[patient.journey_status]}</p></div><div className="actions"><button className="secondary" onClick={()=>setEditing(true)}>Editar ficha</button><button className="danger" onClick={archive}>Arquivar</button></div></div>{patient.care_alert&&<p className="care-alert"><strong>Atenção:</strong> {patient.care_alert}</p>}<dl><div><dt>Próxima ação</dt><dd>{date(patient.next_contact_on)}</dd></div><div><dt>Responsável interno</dt><dd>{patient.assigned_user_name}</dd></div><div><dt>Origem</dt><dd>{sources[patient.contact_source]}</dd></div><div><dt>Responsável pelo paciente</dt><dd>{patient.guardian_name||'Não informado'}</dd></div></dl>{patient.notes&&<p><strong>Observações:</strong> {patient.notes}</p>}</section><div className="record-grid"><form className="panel form" onSubmit={addEvent}><h2>Registrar interação</h2><label>Tipo<select name="eventType" defaultValue="call">{Object.entries(eventTypes).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>O que aconteceu?<textarea name="description" rows={4} minLength={2} required/></label><button>Registrar no histórico</button></form><section className="panel"><h2>Histórico</h2>{timeline.length===0?<p>Nenhuma interação registrada.</p>:<ol className="timeline">{timeline.map(item=><li key={item.id}><strong>{eventTypes[item.type]??'Paciente cadastrado'}</strong><p>{item.description}</p><small>{new Date(item.occurred_at).toLocaleString('pt-BR')} · {item.author}</small></li>)}</ol>}</section></div></>;
}

function Patients(){const [patients,setPatients]=useState<Patient[]>([]),[selected,setSelected]=useState<string|null>(null),[creating,setCreating]=useState(false),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[overdue,setOverdue]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
  async function load(){try{const query=new URLSearchParams({search,...(status&&{status}),...(overdue&&{overdue:'true'})});setPatients((await api(`/api/patients?${query}`)).patients);setError('');}catch(reason){setError((reason as Error).message);}}
  useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer);},[search,status,overdue]);
  if(selected)return <PatientRecord id={selected} onBack={()=>{setSelected(null);load();}}/>;
  if(creating)return <PatientForm onCancel={()=>setCreating(false)} onDone={(id,text)=>{setMessage(text??'Paciente cadastrado.');setCreating(false);setSelected(id);}}/>;
  return <>{message&&<p className="success" role="status">{message}</p>}<div className="toolbar"><label>Buscar paciente<input type="search" placeholder="Nome ou telefone" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos</option>{Object.entries(statuses).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label className="check"><input type="checkbox" checked={overdue} onChange={e=>setOverdue(e.target.checked)}/>Somente atrasados</label><button onClick={()=>setCreating(true)}>+ Novo paciente</button></div>{error&&<p className="error" role="alert">{error}</p>}<section className="panel patient-list"><h2>{patients.length} paciente{patients.length===1?'':'s'}</h2>{patients.length===0?<div className="empty"><h3>Nenhum paciente encontrado</h3><p>Revise os filtros ou cadastre o primeiro paciente.</p></div>:patients.map(patient=><button className="patient-row" onClick={()=>setSelected(patient.id)} key={patient.id}><span><strong>{patient.name}</strong><small>{patient.phone} · {statuses[patient.journey_status]}</small></span><span className={patient.next_contact_on&&patient.next_contact_on<new Date().toISOString().slice(0,10)?'overdue':''}>{patient.next_contact_on?`Contato ${date(patient.next_contact_on)}`:'Sem contato agendado'} →</span></button>)}</section></>;
}

function App(){const [user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[page,setPage]=useState('Início');useEffect(()=>{fetch('/api/auth/me').then(r=>r.ok?r.json():null).then(x=>setUser(x?.user??null)).finally(()=>setLoading(false));},[]);async function login(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setError('');try{const body=await api('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))});setUser(body.user);}catch(reason){setError((reason as Error).message);}}async function logout(){await api('/api/auth/logout',{method:'POST'});setUser(null);}if(loading)return <main className="center" aria-live="polite">Carregando…</main>;if(!user)return <main className="login"><section><span className="brand">Fonolife</span><h1>Entre para cuidar dos seus pacientes</h1><p>Use seu e-mail e senha de acesso.</p><form onSubmit={login}><label>E-mail<input name="email" type="email" autoComplete="username" required autoFocus/></label><label>Senha<input name="password" type="password" autoComplete="current-password" minLength={8} required/></label>{error&&<p className="error" role="alert">{error}</p>}<button>Entrar</button></form><details><summary>Contas da demonstração</summary><p>Admin: admin@demo.local / admin123<br/>Operador: operador@demo.local / operador123</p></details></section></main>;const pages=['Início','Pacientes','Acompanhamento','Financeiro'];return <div className="shell"><header><span className="brand">Fonolife</span><div><span>{user.name}</span><button className="link" onClick={logout}>Sair</button></div></header><nav aria-label="Principal">{pages.map(item=><button className={page===item?'active':''} onClick={()=>setPage(item)} key={item}>{item}</button>)}</nav><main><div className="title"><div><h1>{page}</h1><p>{page==='Pacientes'?'Cadastre e acompanhe cada pessoa em um só lugar.':page==='Início'?'O que precisa da sua atenção hoje.':'Esta área será entregue na próxima etapa.'}</p></div></div>{page==='Pacientes'?<Patients/>:<section className="empty"><h2>{page==='Início'?'Tudo pronto para começar':'Nenhum registro por aqui'}</h2><p>{page==='Início'?'Use Pacientes para iniciar o atendimento.':'Os dados aparecerão aqui nas próximas entregas.'}</p></section>}</main></div>;}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
